version: '3.4'

services:
  actions-runner:
    image: zerosuxx/github-actions-runner:latest
    build:
      context: .
    environment: 
      REPOSITORY_URL: ${REPOSITORY_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
    user: '1000'
